"""Root pytest fixtures for all tests with mock fallbacks."""

import os
os.environ["PYTEST_CURRENT_TEST"] = "pytest"

from pathlib import Path
from typing import Any
from unittest.mock import patch

import pytest

os.environ["SECONDBRAIN_TRACING_ENABLED"] = "false"
os.environ["OTEL_METRICS_ENABLED"] = "false"

# Disable PyTorch meta tensor mode globally to prevent xdist serialization errors
# This must happen before any torch imports occur
try:
    import torch
    if hasattr(torch, "set_default_device"):
        torch.set_default_device("cpu")
except ImportError:
    pass  # PyTorch not installed yet


def pytest_configure(config):
    """Called before any tests are collected."""
    try:
        import torch
        # Force CPU as default device before any model loading
        if hasattr(torch, "set_default_device"):
            torch.set_default_device("cpu")
    except ImportError:
        pass  # PyTorch not available

# Config class will automatically load from .env.test or use platform-aware defaults
from secondbrain.config import get_config

get_config.cache_clear()


def pytest_sessionstart(session: pytest.Session) -> None:
    """Seed MongoDB with minimal test data before tests run.

    IMPORTANT: This hook does NOT generate embeddings to avoid loading the
    SentenceTransformer model at the master process level, which causes
    PyTorch meta tensor errors with pytest-xdist.

    Embeddings are generated by function-scoped fixtures in worker processes
    AFTER xdist spawns workers. This ensures each worker loads its own
    independent model instance.

    Test data here is minimal - just enough to prevent "no data" errors.
    Actual embedding generation happens in worker fixtures.
    """
    import socket
    from contextlib import closing

    # Check if MongoDB is reachable before attempting to seed
    try:
        with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as sock:
            sock.settimeout(2)
            result = sock.connect_ex(("localhost", 27018))
            if result != 0:
                return  # MongoDB not available, skip seeding
    except Exception:
        return  # Network issue, skip seeding

    client = None
    try:
        from secondbrain.config import Config
        from secondbrain.storage import VectorStorage

        config = Config()

        # Use direct MongoDB check
        from pymongo import MongoClient as PyMongoClient

        client = PyMongoClient(config.mongo_uri, serverSelectionTimeoutMS=10000, maxPoolSize=50)
        direct_db = client.get_database(config.mongo_db)
        if "embeddings_test" in direct_db.list_collection_names():
            direct_count = direct_db.embeddings.count_documents({})
        else:
            direct_count = 0

        if direct_count > 0:
            return  # Data already seeded

        # Seed with minimal document metadata only - NO embeddings
        # Actual embeddings will be generated by worker fixtures when needed
        test_documents = [
            {
                "chunk_id": "test-chunk-001",
                "chunk_text": "Test document for testing. This is placeholder text.",
                "source_file": "/test/docs/test.md",
                "file_type": "markdown",
                "metadata": {"title": "Test Document", "page": 1, "test": True},
                # Embedding will be generated by worker fixture, not here
            },
        ]

        # Insert without embeddings - workers will generate them
        collection = direct_db.get_collection("embeddings_test")
        
        if test_documents:
            collection.insert_many(test_documents)
            print(f"Seeded {len(test_documents)} test documents (embeddings generated by worker fixtures)")

    except Exception as e:
        print(f"Warning: Failed to seed test data: {e}")
    finally:
        if client is not None:
            client.close()
def _mock_docker_manager(request):
    """Automatically mock DockerManager to prevent MongoDB startup.
    
    Function scope ensures proper isolation in parallel xdist execution.
    Skipped for tests in test_docker_manager.py which need real DockerManager.
    """
    # Skip mocking for docker_manager tests - they need the real class
    if "test_docker_manager.py" in str(request.path):
        yield
        return
    
    # Create patch per-fixture invocation to avoid worker pollution
    with patch("secondbrain.utils.docker_manager.DockerManager"):
        yield


@pytest.fixture
def sample_pdf_path() -> Path:
    """Return path to a sample PDF file for testing.

    Creates a temporary PDF file with test content using fpdf.
    Skips the test if fpdf is not available.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        pytest.skip("fpdf not installed for PDF creation")

    import tempfile

    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=12)
        pdf.multi_cell(
            0,
            10,
            "SecondBrain test document\n\n"
            "This is sample content for testing PDF ingestion with "
            "machine learning and artificial intelligence topics.",
        )
        pdf.output(tmp.name)
        return Path(tmp.name)


@pytest.fixture
def sample_pdf_with_multiple_pages() -> Path:
    """Return path to a multi-page sample PDF file for testing.

    Creates a temporary multi-page PDF file with test content using fpdf.
    Skips the test if fpdf is not available.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        pytest.skip("fpdf not installed for PDF creation")

    import tempfile

    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        pdf = FPDF()
        for page_num in range(1, 4):
            pdf.add_page()
            pdf.set_font("Arial", size=12)
            pdf.multi_cell(0, 10, f"Page {page_num} of SecondBrain test document\n\n")
            pdf.multi_cell(
                0,
                10,
                f"This is unique content for page {page_num} covering "
                "machine learning, deep learning, and neural networks.",
            )
        pdf.output(tmp.name)
        return Path(tmp.name)


from typing import Any


@pytest.fixture(scope="session")
def embedding_cache() -> Any:
    """Session-scoped embedding cache to prevent repeated generation.

    Caches embeddings by text content to avoid regenerating the same embeddings
    across multiple tests. This provides significant speedup for test suites
    that query the same texts repeatedly.

    Usage:
        def test_something(embedding_cache, embed_gen):
            embedding = embedding_cache("some text", embed_gen)
    """
    cache: dict[str, list[float]] = {}

    def get_or_create(text: str, embed_gen: Any) -> list[float]:
        if text not in cache:
            cache[text] = embed_gen.generate(text)
        return cache[text]

    return get_or_create


# Global mock fixtures for service-independent testing


@pytest.fixture(scope="function")
def mock_llm():
    """Provide MockLLMProviderWithContext for tests.
    
    Returns:
        MockLLMProviderWithContext instance for consistent mock LLM responses.
    """
    from secondbrain.rag.providers.mock import MockLLMProviderWithContext
    return MockLLMProviderWithContext()


@pytest.fixture(scope="function")
def mock_storage():
    """Provide MockVectorStorage for tests.
    
    Returns:
        MockVectorStorage instance for in-memory vector storage.
    """
    from secondbrain.storage import MockVectorStorage
    storage = MockVectorStorage()
    storage.initialize()
    yield storage
    storage.close()


@pytest.fixture(scope="function")
def mock_embedding_gen():
    """Provide MockEmbeddingGenerator for tests.
    
    Returns:
        MockEmbeddingGenerator instance for fast deterministic embeddings.
    """
    from secondbrain.embedding.mock import MockEmbeddingGenerator
    return MockEmbeddingGenerator(model_name="mock-384", dimension=384)


@pytest.fixture(scope="function")
def mock_searcher():
    """Provide MockSearcher for tests.
    
    Returns:
        MockSearcher instance for mock-based search.
    """
    from secondbrain.search.mock import MockSearcher
    return MockSearcher(verbose=False)


@pytest.fixture(scope="session", autouse=True)
def cleanup_mongo_connections():
    """Ensure MongoDB connections are cleaned up after test session.
    
    This fixture runs at the end of the test session to close any lingering
    MongoDB connections that might have been left open by tests.
    """
    yield
    # Cleanup happens here after all tests complete
    import gc
    
    # Force garbage collection to trigger any pending destructors
    gc.collect()


def pytest_sessionfinish(session: pytest.Session, exitstatus: int) -> None:
    """Clean up OpenTelemetry resources after tests complete.
    
    This ensures any OpenTelemetry tracing/metrics resources are properly
    shut down before pytest exits, preventing exporter errors on closed files.
    """
    try:
        from secondbrain.utils.tracing import shutdown_tracing
        shutdown_tracing()
    except Exception:
        # Ignore errors during shutdown - we're already exiting
        pass
